ajax/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/home/index' => 'home#index'
  post '/home/create' => 'home#create'
  get '/home/destroy/:id' => 'home#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ajax/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ajax/app/models/post.rb
class Post < ApplicationRecord
end

ajax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ajax/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @post = Post.new
    @post.content = params[:post][:content]
    
    if @post.save
      respond_to do |format|
        format.js
      end
    end
    # redirect_to '/index'
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      respond_to do |format|
        format.js
      end
    end
    # redirect_to '/index'
  end
end

ajax/app/helpers/application_helper.rb
module ApplicationHelper
end

ajax/app/helpers/home_helper.rb
module HomeHelper
end

ajax/app/views/home/_posts.html.erb
<li id="post-<%=post.id%>">
    <strong>#익명 <%= post.id %>번째 게시물</strong>
    // <%= post.created_at.getlocal("+09:00").strftime("%Y.%m.%d %p %I:%M") %>
    // <%= link_to "삭제", "/home/destroy/#{post.id}",
                                    method: :get,
                                    remote: true,
                                    data: {confirm: "정말로 삭제하시겠습니까?"} %> <br>
    <%= post.content %> 
<br></li>

ajax/app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

ajax/app/views/home/create.js.erb
(function($){
    $("post_content").val("")
    var html = "<%= escape_javascript(render(partial: 'home/posts', locals: {post: @post}))%>";
    $("#posts").append(html);
    })(jQuery)

ajax/app/views/home/destroy.html.erb
<h1>Home#destroy</h1>
<p>Find me in app/views/home/destroy.html.erb</p>

ajax/app/views/home/destroy.js.erb
(function($){
    $("#post-<%=@post.id%>").remove();
})(jQuery)

ajax/app/views/home/index.html.erb
<h1>익명의 게시글을 작성하는 곳입니다</h1>

<%= form_for :post, :url => home_create_path, remote: true do |f| %>
    <%= f.text_area :content %>
    <%= f.submit %>
<% end %>

---------------------------------------------------------------------------------

<h1>게시글</h1>
<p> <ul id="posts">
    <% @posts.each do |post| %>
      <%= render partial: "home/posts", locals: {post: post} %>
    <% end %>
</ul> </p>